-- AlterTable
ALTER TABLE "Issue" ALTER COLUMN "dateAdded" DROP NOT NULL,
ALTER COLUMN "dateAdded" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "expires" DROP NOT NULL,
ALTER COLUMN "expires" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "date" DROP NOT NULL,
ALTER COLUMN "date" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "VerificationToken" ALTER COLUMN "expires" DROP NOT NULL,
ALTER COLUMN "expires" SET DEFAULT CURRENT_TIMESTAMP;
